In [18]:
import numpy as np

A = np.array([[0.1817, 0.5394, -0.1197, 0.6404],
              [0.6198, 0.1994, 0.0946, -0.3121],
              [-0.7634, -0.8181, 0.9883, 0.7018]])

b = np.array([[1.1862, -0.1158, -0.1093]]).T

x = np.zeros((4,1))

print(A)
print(x)
print(b.shape)

[[ 0.1817  0.5394 -0.1197  0.6404]
 [ 0.6198  0.1994  0.0946 -0.3121]
 [-0.7634 -0.8181  0.9883  0.7018]]
[[0.]
 [0.]
 [0.]
 [0.]]
(3, 1)


In [2]:
# OMP
i1 = np.argmax(A.T@b)
print("Column: ", i1+1)

Column:  4


In [3]:
# OMP
As = A[:,np.newaxis,i1]
x[i1] = np.linalg.pinv(As)@b
print("x: ", x)
r1 = b - A@x
print("r1: ", r1)

x:  [[0.        ]
 [0.        ]
 [0.        ]
 [0.71904686]]
r1:  [[ 0.72572239]
 [ 0.10861452]
 [-0.61392708]]


In [6]:
i2 = np.argmax(A.T@r1)
print("Column: ", i2+1)

Column:  2


In [7]:
As

array([[ 0.6404],
       [-0.3121],
       [ 0.7018]])

In [9]:
As = A[:,(i1, i2)]
x[[i1, i2]] = np.linalg.pinv(As)@b
print("x: ", x)
r2 = b - A@x
print("r2: ", r2)

x:  [[0.        ]
 [1.00001139]
 [0.        ]
 [1.00998157]]
r2:  [[1.65905921e-06]
 [1.29754484e-05]
 [4.25644903e-06]]


In [17]:
# LS-OMP
for i in range(4):
    x = np.zeros((4,1))
    As = A[:,np.newaxis,i]
    x[i] = np.linalg.pinv(As)@b
#     print("x: ", x)
    r1 = b - A@x
    print("r1: ", r1)
    print("r1: ", np.sqrt(np.sum(r1**2)))

0.7162132849999999
r1:  [[ 1.14491567]
 [-0.25662567]
 [ 0.06415324]]
r1:  1.1750762854736803
r1:  [[ 0.80529522]
 [-0.25660907]
 [ 0.46841265]]
r1:  0.9663120678925446
r1:  [[ 1.15496305]
 [-0.09111315]
 [ 0.14860708]]
r1:  1.1680433718130576
r1:  [[ 0.72572239]
 [ 0.10861452]
 [-0.61392708]]
r1:  0.9567531400438528


In [26]:
# WMP
t = 0.5
print(t * np.sum(b**2))
for i in range(4):
    if np.abs(A[:,i].T@b) >= t * np.sqrt(np.sum(b**2)):
        break
print("Column: ", i + 1)
print("a_i: ", A[:,i])

0.7162132849999999
Column:  2
a_i:  [ 0.5394  0.1994 -0.8181]


In [36]:
np.argsort(-np.abs(A.T@b), axis=0)

array([[3],
       [1],
       [2],
       [0]])